[package]
name = "cirnum"
version = "0.1.0"
authors = ["Uy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
itertools = "0.13.0"
lopdf = "0.33.0"
chrono = "0.4.38"
